parameters:
#    meet_players_meet_players.example.class: MeetPlayers\MeetPlayersBundle\Example

services:
#    meet_players_meet_players.example:
#        class: %meet_players_meet_players.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
